channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.11.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - ca-certificates
  - openssl
  - pyg
  - certifi
