name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fast_finish: [false]
        python-version: [3.8]
  
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxml2-utils pandoc
          curl -sSL https://install.python-poetry.org | python3 -
          pip install --upgrade pip
          pip install -e ".[cpu,docs]"
      
      - name: Build documentation
        run: |
          sphinx-build -b html docs docs/_build
      
      - name: Get version
        run: |
          VERSION=$(python -c "from scSLAT import __version__; print(__version__)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      
      - name: Create version badge
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: slat_version.json
          label: version
          message: ${{ env.VERSION }}
          color: blue
      
